### ISSUE TITLE
[BUG] Connect4

### ISSUE THREAD

**Issue by StarJules** [aniket091/Gamecord#10]
**Describe the bug**
When the first player clicks any button, the buttons turn into invite buttons.

**To Reproduce**
Follow the steps in the example, but select true in the slash command and change the message to interaction.

**Expected behavior**
The buttons should remain the same, not turning into invitation buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/95444393/207674908-8aef18bb-646e-44aa-899d-e7aa49ba7946.png)

**Please complete the following information:**
- Node Version: v16.15.0
- Gamecord Version: 4.0.0
- Discord.js Version: 14.7.1

**Additional context**
X

**Comment by Liux71** [comment]
same

**Comment by aniket091** [comment]
Fixed in version 4.1.0 and 3.1.0  :D
