### ISSUE TITLE
[BUG] Snake is bugged with custom emojis

### ISSUE THREAD

**Issue by Novampr** [aniket091/Gamecord#20]
**Describe the bug**
When using Snake with custom emojis you can find some odd behaviour, the emoji appears on the first time but after moving the emoji turns into text

**To Reproduce**
Change the snake head to "<:emoji:759436548547>" for example

**Expected behavior**
Description of what you expected to happen.
The emoji does not turn into text

**Screenshots**
Not moved
![image](https://user-images.githubusercontent.com/100384210/232056503-a56d0ee6-a1e9-43fd-8815-c60073017db9.png)
After move
![image](https://user-images.githubusercontent.com/100384210/232056522-f00cbbb4-51c0-4af3-a981-d79dd2d43f0e.png)

**Please complete the following information:**
- Node Version: [18.14.0]
- Gamecord Version: [4.3.0]
- Discord.js Version: [14.8.0]

**Additional context**
No other context

**Comment by Juhan280** [comment]
Does the `@everyone` role has permission to send external emoji?

**Comment by Novampr** [comment]
Yes it does

**Comment by Novampr** [comment]
Also I believe this effects only emojis that are on a different server to the bot

**Comment by TecEash1** [comment]
O Ty lime for askin! It’s good tho. The issue has been fixed :) 
The bot was not in the same server as it got the emoji from. So it got bugged after. 

At least pretty sure it works now. Only thing is emoji not rotating but doesn’t matter that much soo…

**Comment by Novampr** [comment]
I'll keep it open until I can test

If I can't recreate the issue with external emojis then I'll close this issue
