### ISSUE TITLE
No Typescript Feature?

### ISSUE THREAD

**Issue by ghost** [aniket091/Gamecord#24]
So, I tried using discord-gamecord for my discord js v14 bot using typescript, but... I found out that there are no index.d.ts in the project files of discord-gamecord, so there is no way to provide a typescript IntelliSense, please add one!

Thanks,
ContentGamer.

**Comment by ghost** [comment]
found a way to do this by adding //@ts-ignore when importing the package.

**Comment by Juhan280** [comment]
You could also try #16 
Although that is 2 versions behind the version in npm because the author of the repo didn't push the changes to the repo
