### ISSUE TITLE
Embed Parts are Deprecated.

### ISSUE THREAD

**Issue by SRBAPH** [aniket091/Gamecord#4]
I was thinking that developers should update all of the Embed parts so there will be no deprecation warning on users console.

**Comment by aniket091** [comment]
We are working on the update and all the embeds will be updated by the next Update :D

**Comment by SRBAPH** [comment]
> We are working on the update and all the embeds will be updated by the next Update :D

ok! thanks!

**Comment by aniket091** [comment]
Closing the issue :D
